### ISSUE TITLE
Select cloud storage as directory

### ISSUE THREAD

**Issue by qol3m** [39aldo39/DecSync#24]
EDIT: Sorry, I think I created this issue in the wrong place. https://github.com/39aldo39/DecSyncCC/issues/45

It appears that many/most/all cloud storage solutions are embedded into the file browser in Android. (?) (for example pcloud) This allows you to browse and use the cloud storage like a regular folder on your device.

It would be great if I could set my cloud storage as DecSync directory. This would eliminate the need for a separate sync app for many users, as most cloud storage apps don't allow for mobile sync and in many cases not even backup besides photos and videos.

The password manager Keepass2Android supports this for its password database, if you need a code example https://github.com/PhilippC/keepass2android  . I don't know anything about Android development, but it appears one only has to adjust the folder picker code?

Thanks for this app. It's much better than running a separate CardDAV/CalDAV server just to sync a few bits of text.

**Comment by jeroenev** [comment]
can this be re-opened?
I think using the default android file-picker would already help a lot, instead of the current custom implementation that doesn't really support anything except raw local storage.
Using the android file-picker we can select mounted cloud providers as our file location, like pCloud, Mega, dropbox and many others.

I'm also assuming using the android file-picker would reduce the amount of code and maintenance needed in the future.
