### ISSUE TITLE
v2 Draft Status

### ISSUE THREAD

**Issue by Alch-Emi** [39aldo39/DecSync#28]
Howdy!

I'm curious if there's an update about the version two spec.  I'm in the process of drafting (no promises, just testing the water atm) a rust implementation of decsync, but I'm not sure how I should handle the version 2 spec.  As I see it, my options are:

- Implement v2 completely & by default
- Add support, but use v1 by default
- Don't implement v2, but leave the framework modular enough to support a non-backwards-compatible change
- Focus exclusively on adding v1

Since it seems like most other apps use the v1 format, I'd normally lean towards the second option, but it seems like the v2 draft has been stagnant for a considerable amount of time, with most apps not using it.

I'm curious about when you predict the v2 spec will be officiated, and more importantly, implemented in official libs, especially since it seems like apps programmed without v2 support will be unable to read v2 collections, so before any v2 collections can be created, most of the implementations need to be able to read from it.

Thank you for the help!

**Comment by 39aldo39** [comment]
Yes, the v2 draft has been stagnant for a while, mainly because I wanted to make sure I wouldn't change it. But I should just finalize it soon.

As for your options the second one is indeed preferred. My idea is the following:
- Only support v1 (current situation)
- Add support for v2, but use v1 by default (your second option, which libdecsync should do soon)
- Once all apps have added support for v2 and should be upgraded, make v2 default and convert old v1 directories automatically
