### ISSUE TITLE
V1 clearing

### ISSUE THREAD

**Issue by cinghiopinghio** [39aldo39/DecSync#36]
Dear @39aldo39 ,
I've been looking for this information without success.

I understand that the new protocol version v2 will overcome some shortcomings, namely more efficient data storage with a lower number of files.

I would like to clean my syncing directory.
When all my devices are updated to the new version, can I somehow clean the file structure? I have more than 5000 files to sync and syncthing scales with the number of files...

At the moment I'm using `DecSyncCC` and  `Radicale-DecSync`.

**Comment by 39aldo39** [comment]
It is now possible to clean it! In DecSync CC you can press the dots on any collection and press 'Manage DecSync data'. This allows you to delete any unused apps. The v1 files should be automatically deleted when upgraded to v2 (but only for the app that upgrades), although it may not finish because it can take a while.
