### ISSUE TITLE
Support for Thunderbird 

### ISSUE THREAD

**Issue by dessalines** [39aldo39/DecSync#9]
There are a few of us that would love Thunderbird support.

**Comment by 39aldo39** [comment]
I didn't plan support for Thunderbird, but it looks like quite some people want it. I explored the possibility a bit, but it looks like there are a few technical difficulties. Modern add-ons (WebExtensions) don't have access to the filesystem, which is crucial for DecSync. However, it is also possible for an add-on to communicate with a program on the computer, so that may be a solution. I will look further into it.

**Comment by 39aldo39** [comment]
Update on the approach: I think a storage plugin for the CalDAV/CardDAV server Radicale, similar to [EteSync](https://github.com/etesync/radicale_storage_etesync) is an easier and more universal approach. I don't have a lot of time right now, so it won't come very soon, but it is feasible.

**Comment by kocjs** [comment]
It might be of use, [TbSync](https://github.com/jobisoft/TbSync), from there repository.   

Introduction

TbSync is a central user interface to manage cloud accounts and to synchronize their contact, task and calendar information with Thunderbird. Its main objective is to simplify the setup process for such accounts. The following providers (protocols) are currently supported:

    CalDAV & CardDAV, via DAV-4-TbSync [compatibility list (DAV)]
    Exchange ActiveSync (EAS v2.5 & v14.0), via EAS-4-TbSync [compatibility list (EAS)]

Further details can be found in the wiki of the TbSync project and in the how-to-get-started guide.

If you like TbSync and want to support its development, please consider a donation.

**Comment by 39aldo39** [comment]
The Radicale plugin is finished! See [Radicale-DecSync](https://github.com/39aldo39/Radicale-DecSync) for the repo. This means that it should be possible to use DecSync wit Thunderbird, among others.

**Comment by kocjs** [comment]
How do should I import tasks to Thunderbird lightning?
